# UppASD

In [1]:
from mammos_spindynamics import uppasd

We start by defining a simulation object.
This object defines the location of the UppASD input files.

In [2]:
sim = uppasd.Simulation(
    jfile="uppasd_data/jfile",
    momfile="uppasd_data/momfile",
    posfile="uppasd_data/posfile",
    inpsd="uppasd_data/inpsd-short.dat",
)
sim

Simulation(jfile=PosixPath('uppasd_data/jfile'), momfile=PosixPath('uppasd_data/momfile'), posfile=PosixPath('uppasd_data/posfile'), inpsd=PosixPath('uppasd_data/inpsd-short.dat'))

## Single calculation: default `run` runner

We can run a single UppASD run specifying the temperature and other parameters we want to modify in `inpsd.dat`.

In [3]:
sim.run(
    T=10,
    mcNstep=700,
)

 --------------------------------------------------------------
             __  __          ___   _______    ____  ___
            / / / /__  ___  / _ | / __/ _ \  / __/ / _ \
           / /_/ / _ \/ _ \/ __ |_\ \/ // / / _ \_/ // /
           \____/ .__/ .__/_/ |_/___/____/  \___(_)___/
               /_/  /_/
 --------------------------------------------------------------
                https://github.com/UppASD/UppASD
 --------------------------------------------------------------
              Division of Materials Theory
              Department of Physics and Astronomy
              Uppsala University
              Sweden
 ---------------------Production-version-----------------------
 Git revision: v6.0.2-136-g553a
 --------------------------------------------------------------
 RNG: Mersenne-Twister (mtprng)
 --------------------------------------------------------------
 Execution Date: 04/11/2025  Execution Time: 13:37:13:690
 --------------------------------------------------------------
 Using OpenMP with 16  threads out of 16 possible.
 --------------------------------------------------------------
 Read input file using new format
 done.
  Set up types of atoms done
  Set up chemical information of alloy done
  Set up global coordinates done
  Set up damping
  done
  Set up temperature
  done
 Set up q-vectors
 Allocate spin-correlation data
 Write input data done.
 Set up Hamiltonian
  Set up neighbour map for exchange nntype           9           0
 done
  Mount Heisenberg Hamiltonian done
  Print exchange interaction strengths done
  Calculate mean-field estimate of Tc:     0.0 K.
  Max eigenvalue:     0.000 meV
  Min eigenvalue:     0.000 meV
 Initialize metatype
 Initialize magnetic moments
  Moments from inpsd.dat  done
 Mounting A-matrix for AMS calculation done.
  Tc-MFA from AMS:       0.0
  Tc-RPA from AMS:       NaN
 Adiabatic Magnon Spectra Calculations done.
 Calculate the ferromagnetic stiffness  Tc-MFA from stiffness :       0.0  K
 done
 Enter initial phase:  M
Performing MC initial phase:  1    Temp:   10.00       MCS/s:       1200    Mode:         M
  IP MC    10% done. Mbar:  0.007415
  IP MC    20% done. Mbar:  0.004192
  IP MC    30% done. Mbar:  0.004515
  IP MC    40% done. Mbar:  0.005331
  IP MC    50% done. Mbar:  0.008997
  IP MC    60% done. Mbar:  0.007946
  IP MC    70% done. Mbar:  0.006985
  IP MC    80% done. Mbar:  0.007083  U(L):  0.405588  X:  0.015669
  IP MC    90% done. Mbar:  0.008596  U(L):  0.416862  X:  0.014917
  IP MC   100% done. Mbar:  0.005482  U(L):  0.424698  X:  0.014186
 Enter measurement phase:
  MP MC   5% done. Mbar:  0.005200. Ebar:    0.000000. U: 0.00000.
  MP MC  10% done. Mbar:  0.002807. Ebar:    0.000000. U: 0.66667.
  MP MC  15% done. Mbar:  0.004863. Ebar:    0.000000. U: 0.64876.
  MP MC  20% done. Mbar:  0.005991. Ebar:    0.000000. U: 0.64876.
  MP MC  25% done. Mbar:  0.002619. Ebar:    0.000000. U: 0.48590.
  MP MC  30% done. Mbar:  0.004200. Ebar:    0.000000. U: 0.56445.
  MP MC  35% done. Mbar:  0.002095. Ebar:    0.000000. U: 0.56445.
  MP MC  40% done. Mbar:  0.009934. Ebar:    0.000000. U: 0.53178.
  MP MC  45% done. Mbar:  0.002771. Ebar:    0.000000. U: 0.50898.
  MP MC  50% done. Mbar:  0.011051. Ebar:    0.000000. U: 0.38790.
  MP MC  55% done. Mbar:  0.004691. Ebar:    0.000000. U: 0.38790.
  MP MC  60% done. Mbar:  0.002230. Ebar:    0.000000. U: 0.40974.
  MP MC  65% done. Mbar:  0.006284. Ebar:    0.000000. U: 0.39146.
  MP MC  70% done. Mbar:  0.008338. Ebar:    0.000000. U: 0.39146.
  MP MC  75% done. Mbar:  0.008267. Ebar:    0.000000. U: 0.46547.
  MP MC  80% done. Mbar:  0.004928. Ebar:    0.000000. U: 0.51227.
  MP MC  85% done. Mbar:  0.004186. Ebar:    0.000000. U: 0.51227.
  MP MC  90% done. Mbar:  0.006781. Ebar:    0.000000. U: 0.44564.
  MP MC  95% done. Mbar:  0.007011. Ebar:    0.000000. U: 0.36796.
  MP MC 100% done. Mbar:  0.002990. Ebar:    0.000000. U: 0.27871.
  Correlation lengths:      0.00000     13.47990       106.56
 Simulation finished
 ----------------TIME CONSUMPTION REPORT----------------------
 CATEGORY                 TIME(sec)           PERCENT
  Startup                  9.93E-02               0.2
  Initial                  7.93E+00              12.4
  Measurement              9.21E-02               0.1
  MonteCarlo               5.03E+00               7.9
  Energy                   5.31E-02               0.1
  PrintRestart             3.81E-02               0.1
  SpinCorr                 5.06E+01              79.0
 -------------------------------------------------------------
 Total wall time           6.40E+01      Sampled percent  99.7
 --------------MAIN PROGRAM PHASES TIME REPORT----------------
 CATEGORY                   EXECUTION TIME    TOTAL CPU TIME
  Time for initialization :           0.87              1.74
  Time for initial phase  :           9.31            127.38
  Time for meas. phase    :          59.32            895.33
  Time for cleanup        :           0.00              0.03
 -------------------------------------------------------------
  Time total              :          69.51           1024.49
  Time for one meas. iter :          59.32            895.33
 -------------------MEMORY CONSUMPTION REPORT-----------------------
 130 allocations and 125 deallocations, remaining memory(B):504
 Memory occupation peak: 201460 kB
 For the array: "D_matrix" in routine "ferro_stiffness"
 -----------------END MEMORY CONSUMPTION REPORT---------------------

In particular, we can see the values `temp 10` and `mcNstep 700` in the file `inpsd.dat`.

In [4]:
with open("out/run_0/inpsd.dat") as f:
    print(f.read())

simid bccFe100
ncell     25       25      25                System size
BC        P         P         P                 Boundary conditions (0=vacuum, P=periodic)
cell          5.0575886562   -2.9200001721    0.0000000000
              0.0000000000    5.8400003443    0.0000000000
              0.0000000000    0.0000000000    3.5140002072
Sym       0                                     Symmetry of lattice (0 for no, 1 for cubic, 2 for 2d cubic, 3 for hexagonal)

posfile   ./posfile
posfiletype D
momfile   ./momfile
exchange  ./jASD2
#anisotropy ./kfile

do_ralloy 0
Mensemble 1
tseed 4499
maptype 3

SDEalgh   1                                     SDE solver: 1=midpoint, 2=heun, 3=heun3, 4=Heun_proper, 5=Depondt
Initmag   3                                     Initial config of moments (1=random, 2=cone, 3=spec., 4=file)
#restartfile ./restart.bccFe100.out

ip_mode   M                                     Initial phase parameters
ip_mcanneal 1                                 --
1200 10 1.00e-16 0.3                      --

mode      M                                     S=SD, M=MC
temp 10
mcNstep 700
damping 0.1
timestep 1.0e-16

do_avrg   Y                                     Measure averages

do_cumu Y
cumu_step 50
cumu_buff 10

do_tottraj N                                    Measure moments
tottraj_step   1000

plotenergy 1

do_sc C
do_ams Y
do_magdos Y
magdos_freq 200
magdos_sigma 30
qpoints C

do_stiffness Y
eta_max 12
eta_min 6
alat 1.00e-10

do_prnstruct 1
do_tottraj Y
do_proj_avrg Y

## Serial calculation: iterate default `run` runner

We can repeat different UppASD runs using different temperatures to generate different output directories.

In [5]:
for T in [2, 5]:
    sim.run(
        T=T,
        mcNstep=700,
    )

 --------------------------------------------------------------
             __  __          ___   _______    ____  ___
            / / / /__  ___  / _ | / __/ _ \  / __/ / _ \
           / /_/ / _ \/ _ \/ __ |_\ \/ // / / _ \_/ // /
           \____/ .__/ .__/_/ |_/___/____/  \___(_)___/
               /_/  /_/
 --------------------------------------------------------------
                https://github.com/UppASD/UppASD
 --------------------------------------------------------------
              Division of Materials Theory
              Department of Physics and Astronomy
              Uppsala University
              Sweden
 ---------------------Production-version-----------------------
 Git revision: v6.0.2-136-g553a
 --------------------------------------------------------------
 RNG: Mersenne-Twister (mtprng)
 --------------------------------------------------------------
 Execution Date: 04/11/2025  Execution Time: 13:38:23:324
 --------------------------------------------------------------
 Using OpenMP with 16  threads out of 16 possible.
 --------------------------------------------------------------
 Read input file using new format
 done.
  Set up types of atoms done
  Set up chemical information of alloy done
  Set up global coordinates done
  Set up damping
  done
  Set up temperature
  done
 Set up q-vectors
 Allocate spin-correlation data
 Write input data done.
 Set up Hamiltonian
  Set up neighbour map for exchange nntype           9           0
 done
  Mount Heisenberg Hamiltonian done
  Print exchange interaction strengths done
  Calculate mean-field estimate of Tc:     0.0 K.
  Max eigenvalue:     0.000 meV
  Min eigenvalue:     0.000 meV
 Initialize metatype
 Initialize magnetic moments
  Moments from inpsd.dat  done
 Mounting A-matrix for AMS calculation done.
  Tc-MFA from AMS:       0.0
  Tc-RPA from AMS:       NaN
 Adiabatic Magnon Spectra Calculations done.
 Calculate the ferromagnetic stiffness  Tc-MFA from stiffness :       0.0  K
 done
 Enter initial phase:  M
Performing MC initial phase:  1    Temp:   2.000       MCS/s:       1200    Mode:         M
  IP MC    10% done. Mbar:  0.007681
  IP MC    20% done. Mbar:  0.004142
  IP MC    30% done. Mbar:  0.004367
  IP MC    40% done. Mbar:  0.005317
  IP MC    50% done. Mbar:  0.009090
  IP MC    60% done. Mbar:  0.007975
  IP MC    70% done. Mbar:  0.007136
  IP MC    80% done. Mbar:  0.007169  U(L):  0.403429  X:  0.079758
  IP MC    90% done. Mbar:  0.008503  U(L):  0.414224  X:  0.075849
  IP MC   100% done. Mbar:  0.005479  U(L):  0.421647  X:  0.072167
 Enter measurement phase:
  MP MC   5% done. Mbar:  0.005186. Ebar:    0.000000. U: 0.00000.
  MP MC  10% done. Mbar:  0.002892. Ebar:    0.000000. U: 0.66667.
  MP MC  15% done. Mbar:  0.004989. Ebar:    0.000000. U: 0.64797.
  MP MC  20% done. Mbar:  0.005923. Ebar:    0.000000. U: 0.64797.
  MP MC  25% done. Mbar:  0.002640. Ebar:    0.000000. U: 0.48474.
  MP MC  30% done. Mbar:  0.004170. Ebar:    0.000000. U: 0.56837.
  MP MC  35% done. Mbar:  0.002187. Ebar:    0.000000. U: 0.56837.
  MP MC  40% done. Mbar:  0.010199. Ebar:    0.000000. U: 0.53101.
  MP MC  45% done. Mbar:  0.002813. Ebar:    0.000000. U: 0.50203.
  MP MC  50% done. Mbar:  0.011135. Ebar:    0.000000. U: 0.37967.
  MP MC  55% done. Mbar:  0.004731. Ebar:    0.000000. U: 0.37967.
  MP MC  60% done. Mbar:  0.002205. Ebar:    0.000000. U: 0.39727.
  MP MC  65% done. Mbar:  0.006246. Ebar:    0.000000. U: 0.37767.
  MP MC  70% done. Mbar:  0.008177. Ebar:    0.000000. U: 0.37767.
  MP MC  75% done. Mbar:  0.008230. Ebar:    0.000000. U: 0.45935.
  MP MC  80% done. Mbar:  0.004723. Ebar:    0.000000. U: 0.50682.
  MP MC  85% done. Mbar:  0.004316. Ebar:    0.000000. U: 0.50682.
  MP MC  90% done. Mbar:  0.006919. Ebar:    0.000000. U: 0.44249.
  MP MC  95% done. Mbar:  0.007068. Ebar:    0.000000. U: 0.36286.
  MP MC 100% done. Mbar:  0.003041. Ebar:    0.000000. U: 0.27219.
  Correlation lengths:      0.00000     14.06087       110.64
 Simulation finished
 ----------------TIME CONSUMPTION REPORT----------------------
 CATEGORY                 TIME(sec)           PERCENT
  Startup                  9.17E-02               0.1
  Initial                  8.15E+00              12.6
  Measurement              5.68E-02               0.1
  MonteCarlo               4.72E+00               7.3
  Energy                   4.84E-02               0.1
  PrintRestart             4.29E-02               0.1
  SpinCorr                 5.14E+01              79.6
 -------------------------------------------------------------
 Total wall time           6.46E+01      Sampled percent  99.9
 --------------MAIN PROGRAM PHASES TIME REPORT----------------
 CATEGORY                   EXECUTION TIME    TOTAL CPU TIME
  Time for initialization :           0.89              1.60
  Time for initial phase  :           9.54            131.00
  Time for meas. phase    :          59.53            900.29
  Time for cleanup        :           0.00              0.03
 -------------------------------------------------------------
  Time total              :          69.97           1032.92
  Time for one meas. iter :          59.53            900.29
 -------------------MEMORY CONSUMPTION REPORT-----------------------
 130 allocations and 125 deallocations, remaining memory(B):504
 Memory occupation peak: 201460 kB
 For the array: "D_matrix" in routine "ferro_stiffness"
 -----------------END MEMORY CONSUMPTION REPORT---------------------
 --------------------------------------------------------------
             __  __          ___   _______    ____  ___
            / / / /__  ___  / _ | / __/ _ \  / __/ / _ \
           / /_/ / _ \/ _ \/ __ |_\ \/ // / / _ \_/ // /
           \____/ .__/ .__/_/ |_/___/____/  \___(_)___/
               /_/  /_/
 --------------------------------------------------------------
                https://github.com/UppASD/UppASD
 --------------------------------------------------------------
              Division of Materials Theory
              Department of Physics and Astronomy
              Uppsala University
              Sweden
 ---------------------Production-version-----------------------
 Git revision: v6.0.2-136-g553a
 --------------------------------------------------------------
 RNG: Mersenne-Twister (mtprng)
 --------------------------------------------------------------
 Execution Date: 04/11/2025  Execution Time: 13:39:33:371
 --------------------------------------------------------------
 Using OpenMP with 16  threads out of 16 possible.
 --------------------------------------------------------------
 Read input file using new format
 done.
  Set up types of atoms done
  Set up chemical information of alloy done
  Set up global coordinates done
  Set up damping
  done
  Set up temperature
  done
 Set up q-vectors
 Allocate spin-correlation data
 Write input data done.
 Set up Hamiltonian
  Set up neighbour map for exchange nntype           9           0
 done
  Mount Heisenberg Hamiltonian done
  Print exchange interaction strengths done
  Calculate mean-field estimate of Tc:     0.0 K.
  Max eigenvalue:     0.000 meV
  Min eigenvalue:     0.000 meV
 Initialize metatype
 Initialize magnetic moments
  Moments from inpsd.dat  done
 Mounting A-matrix for AMS calculation done.
  Tc-MFA from AMS:       0.0
  Tc-RPA from AMS:       NaN
 Adiabatic Magnon Spectra Calculations done.
 Calculate the ferromagnetic stiffness  Tc-MFA from stiffness :       0.0  K
 done
 Enter initial phase:  M
Performing MC initial phase:  1    Temp:   5.000       MCS/s:       1200    Mode:         M
  IP MC    10% done. Mbar:  0.007545
  IP MC    20% done. Mbar:  0.004171
  IP MC    30% done. Mbar:  0.004440
  IP MC    40% done. Mbar:  0.005329
  IP MC    50% done. Mbar:  0.009050
  IP MC    60% done. Mbar:  0.007965
  IP MC    70% done. Mbar:  0.007055
  IP MC    80% done. Mbar:  0.007128  U(L):  0.404585  X:  0.031636
  IP MC    90% done. Mbar:  0.008558  U(L):  0.415639  X:  0.030100
  IP MC   100% done. Mbar:  0.005482  U(L):  0.423273  X:  0.028630
 Enter measurement phase:
  MP MC   5% done. Mbar:  0.005195. Ebar:    0.000000. U: 0.00000.
  MP MC  10% done. Mbar:  0.002847. Ebar:    0.000000. U: 0.66667.
  MP MC  15% done. Mbar:  0.004925. Ebar:    0.000000. U: 0.64827.
  MP MC  20% done. Mbar:  0.005959. Ebar:    0.000000. U: 0.64827.
  MP MC  25% done. Mbar:  0.002627. Ebar:    0.000000. U: 0.48502.
  MP MC  30% done. Mbar:  0.004184. Ebar:    0.000000. U: 0.56640.
  MP MC  35% done. Mbar:  0.002139. Ebar:    0.000000. U: 0.56640.
  MP MC  40% done. Mbar:  0.010061. Ebar:    0.000000. U: 0.53165.
  MP MC  45% done. Mbar:  0.002793. Ebar:    0.000000. U: 0.50601.
  MP MC  50% done. Mbar:  0.011094. Ebar:    0.000000. U: 0.38431.
  MP MC  55% done. Mbar:  0.004709. Ebar:    0.000000. U: 0.38431.
  MP MC  60% done. Mbar:  0.002217. Ebar:    0.000000. U: 0.40403.
  MP MC  65% done. Mbar:  0.006269. Ebar:    0.000000. U: 0.38473.
  MP MC  70% done. Mbar:  0.008258. Ebar:    0.000000. U: 0.38473.
  MP MC  75% done. Mbar:  0.008251. Ebar:    0.000000. U: 0.46254.
  MP MC  80% done. Mbar:  0.004832. Ebar:    0.000000. U: 0.50970.
  MP MC  85% done. Mbar:  0.004251. Ebar:    0.000000. U: 0.50970.
  MP MC  90% done. Mbar:  0.006849. Ebar:    0.000000. U: 0.44416.
  MP MC  95% done. Mbar:  0.007039. Ebar:    0.000000. U: 0.36549.
  MP MC 100% done. Mbar:  0.003013. Ebar:    0.000000. U: 0.27551.
  Correlation lengths:      0.00000     13.70602       108.50
 Simulation finished
 ----------------TIME CONSUMPTION REPORT----------------------
 CATEGORY                 TIME(sec)           PERCENT
  Startup                  1.01E-01               0.2
  Initial                  8.00E+00              12.4
  Measurement              5.10E-02               0.1
  MonteCarlo               4.68E+00               7.2
  Energy                   4.14E-02               0.1
  PrintRestart             4.02E-02               0.1
  SpinCorr                 5.16E+01              79.9
 -------------------------------------------------------------
 Total wall time           6.46E+01      Sampled percent  99.9
 --------------MAIN PROGRAM PHASES TIME REPORT----------------
 CATEGORY                   EXECUTION TIME    TOTAL CPU TIME
  Time for initialization :           0.89              1.72
  Time for initial phase  :           9.49            128.56
  Time for meas. phase    :          59.63            903.64
  Time for cleanup        :           0.00              0.01
 -------------------------------------------------------------
  Time total              :          70.01           1033.94
  Time for one meas. iter :          59.63            903.64
 -------------------MEMORY CONSUMPTION REPORT-----------------------
 130 allocations and 125 deallocations, remaining memory(B):504
 Memory occupation peak: 201460 kB
 For the array: "D_matrix" in routine "ferro_stiffness"
 -----------------END MEMORY CONSUMPTION REPORT---------------------

## Serial calculation: `temparray` runner

We can use the `temparray` runner to run the simulation using different temperatures.

This will create a `run_temparray_<idx>` in the output directory (by default called `out`).
The index `idx` is the first non negative integer available.

In [6]:
sim.run_temparray(
    T_array=[2, 5],
    mcNstep=700,
)

 --------------------------------------------------------------
             __  __          ___   _______    ____  ___
            / / / /__  ___  / _ | / __/ _ \  / __/ / _ \
           / /_/ / _ \/ _ \/ __ |_\ \/ // / / _ \_/ // /
           \____/ .__/ .__/_/ |_/___/____/  \___(_)___/
               /_/  /_/
 --------------------------------------------------------------
                https://github.com/UppASD/UppASD
 --------------------------------------------------------------
              Division of Materials Theory
              Department of Physics and Astronomy
              Uppsala University
              Sweden
 ---------------------Production-version-----------------------
 Git revision: v6.0.2-136-g553a
 --------------------------------------------------------------
 RNG: Mersenne-Twister (mtprng)
 --------------------------------------------------------------
 Execution Date: 04/11/2025  Execution Time: 13:40:43:466
 --------------------------------------------------------------
 Using OpenMP with 16  threads out of 16 possible.
 --------------------------------------------------------------
 Read input file using new format
 done.
  Set up types of atoms done
  Set up chemical information of alloy done
  Set up global coordinates done
  Set up damping
  done
  Set up temperature
  done
 Set up q-vectors
 Allocate spin-correlation data
 Write input data done.
 Set up Hamiltonian
  Set up neighbour map for exchange nntype           9           0
 done
  Mount Heisenberg Hamiltonian done
  Print exchange interaction strengths done
  Calculate mean-field estimate of Tc:     0.0 K.
  Max eigenvalue:     0.000 meV
  Min eigenvalue:     0.000 meV
 Initialize metatype
 Initialize magnetic moments
  Moments from inpsd.dat  done
 Mounting A-matrix for AMS calculation done.
  Tc-MFA from AMS:       0.0
  Tc-RPA from AMS:       NaN
 Adiabatic Magnon Spectra Calculations done.
 Calculate the ferromagnetic stiffness  Tc-MFA from stiffness :       0.0  K
 done
 Enter initial phase:  M
Performing MC initial phase:  1    Temp:   2.000       MCS/s:       1200    Mode:         M
  IP MC    10% done. Mbar:  0.007681
  IP MC    20% done. Mbar:  0.004142
  IP MC    30% done. Mbar:  0.004367
  IP MC    40% done. Mbar:  0.005317
  IP MC    50% done. Mbar:  0.009090
  IP MC    60% done. Mbar:  0.007975
  IP MC    70% done. Mbar:  0.007136
  IP MC    80% done. Mbar:  0.007169  U(L):  0.403429  X:  0.079758
  IP MC    90% done. Mbar:  0.008503  U(L):  0.414224  X:  0.075849
  IP MC   100% done. Mbar:  0.005479  U(L):  0.421647  X:  0.072167
 Enter measurement phase:
  MP MC   5% done. Mbar:  0.005186. Ebar:    0.000000. U: 0.00000.
  MP MC  10% done. Mbar:  0.002892. Ebar:    0.000000. U: 0.66667.
  MP MC  15% done. Mbar:  0.004989. Ebar:    0.000000. U: 0.64797.
  MP MC  20% done. Mbar:  0.005923. Ebar:    0.000000. U: 0.64797.
  MP MC  25% done. Mbar:  0.002640. Ebar:    0.000000. U: 0.48474.
  MP MC  30% done. Mbar:  0.004170. Ebar:    0.000000. U: 0.56837.
  MP MC  35% done. Mbar:  0.002187. Ebar:    0.000000. U: 0.56837.
  MP MC  40% done. Mbar:  0.010199. Ebar:    0.000000. U: 0.53101.
  MP MC  45% done. Mbar:  0.002813. Ebar:    0.000000. U: 0.50203.
  MP MC  50% done. Mbar:  0.011135. Ebar:    0.000000. U: 0.37967.
  MP MC  55% done. Mbar:  0.004731. Ebar:    0.000000. U: 0.37967.
  MP MC  60% done. Mbar:  0.002205. Ebar:    0.000000. U: 0.39727.
  MP MC  65% done. Mbar:  0.006246. Ebar:    0.000000. U: 0.37767.
  MP MC  70% done. Mbar:  0.008177. Ebar:    0.000000. U: 0.37767.
  MP MC  75% done. Mbar:  0.008230. Ebar:    0.000000. U: 0.45935.
  MP MC  80% done. Mbar:  0.004723. Ebar:    0.000000. U: 0.50682.
  MP MC  85% done. Mbar:  0.004316. Ebar:    0.000000. U: 0.50682.
  MP MC  90% done. Mbar:  0.006919. Ebar:    0.000000. U: 0.44249.
  MP MC  95% done. Mbar:  0.007068. Ebar:    0.000000. U: 0.36286.
  MP MC 100% done. Mbar:  0.003041. Ebar:    0.000000. U: 0.27219.
  Correlation lengths:      0.00000     14.06087       110.64
 Simulation finished
 ----------------TIME CONSUMPTION REPORT----------------------
 CATEGORY                 TIME(sec)           PERCENT
  Startup                  9.99E-02               0.2
  Initial                  7.94E+00              12.2
  Measurement              6.06E-02               0.1
  MonteCarlo               4.72E+00               7.2
  Energy                   4.14E-02               0.1
  PrintRestart             4.27E-02               0.1
  SpinCorr                 5.21E+01              80.0
 -------------------------------------------------------------
 Total wall time           6.51E+01      Sampled percent  99.8
 --------------MAIN PROGRAM PHASES TIME REPORT----------------
 CATEGORY                   EXECUTION TIME    TOTAL CPU TIME
  Time for initialization :           0.91              1.87
  Time for initial phase  :           9.40            127.66
  Time for meas. phase    :          60.14            911.79
  Time for cleanup        :           0.01              0.12
 -------------------------------------------------------------
  Time total              :          70.45           1041.44
  Time for one meas. iter :          60.14            911.79
 -------------------MEMORY CONSUMPTION REPORT-----------------------
 130 allocations and 125 deallocations, remaining memory(B):504
 Memory occupation peak: 201460 kB
 For the array: "D_matrix" in routine "ferro_stiffness"
 -----------------END MEMORY CONSUMPTION REPORT---------------------
 --------------------------------------------------------------
             __  __          ___   _______    ____  ___
            / / / /__  ___  / _ | / __/ _ \  / __/ / _ \
           / /_/ / _ \/ _ \/ __ |_\ \/ // / / _ \_/ // /
           \____/ .__/ .__/_/ |_/___/____/  \___(_)___/
               /_/  /_/
 --------------------------------------------------------------
                https://github.com/UppASD/UppASD
 --------------------------------------------------------------
              Division of Materials Theory
              Department of Physics and Astronomy
              Uppsala University
              Sweden
 ---------------------Production-version-----------------------
 Git revision: v6.0.2-136-g553a
 --------------------------------------------------------------
 RNG: Mersenne-Twister (mtprng)
 --------------------------------------------------------------
 Execution Date: 04/11/2025  Execution Time: 13:41:54:002
 --------------------------------------------------------------
 Using OpenMP with 16  threads out of 16 possible.
 --------------------------------------------------------------
 Read input file using new format
 done.
  Set up types of atoms done
  Set up chemical information of alloy done
  Set up global coordinates done
  Set up damping
  done
  Set up temperature
  done
 Set up q-vectors
 Allocate spin-correlation data
 Write input data done.
 Set up Hamiltonian
  Set up neighbour map for exchange nntype           9           0
 done
  Mount Heisenberg Hamiltonian done
  Print exchange interaction strengths done
  Calculate mean-field estimate of Tc:     0.0 K.
  Max eigenvalue:     0.000 meV
  Min eigenvalue:     0.000 meV
 Initialize metatype
 Initialize magnetic moments
  Moments from inpsd.dat  done
 Mounting A-matrix for AMS calculation done.
  Tc-MFA from AMS:       0.0
  Tc-RPA from AMS:       NaN
 Adiabatic Magnon Spectra Calculations done.
 Calculate the ferromagnetic stiffness  Tc-MFA from stiffness :       0.0  K
 done
 Enter initial phase:  M
Performing MC initial phase:  1    Temp:   5.000       MCS/s:       1200    Mode:         M
  IP MC    10% done. Mbar:  0.007545
  IP MC    20% done. Mbar:  0.004171
  IP MC    30% done. Mbar:  0.004440
  IP MC    40% done. Mbar:  0.005329
  IP MC    50% done. Mbar:  0.009050
  IP MC    60% done. Mbar:  0.007965
  IP MC    70% done. Mbar:  0.007055
  IP MC    80% done. Mbar:  0.007128  U(L):  0.404585  X:  0.031636
  IP MC    90% done. Mbar:  0.008558  U(L):  0.415639  X:  0.030100
  IP MC   100% done. Mbar:  0.005482  U(L):  0.423273  X:  0.028630
 Enter measurement phase:
  MP MC   5% done. Mbar:  0.005195. Ebar:    0.000000. U: 0.00000.
  MP MC  10% done. Mbar:  0.002847. Ebar:    0.000000. U: 0.66667.
  MP MC  15% done. Mbar:  0.004925. Ebar:    0.000000. U: 0.64827.
  MP MC  20% done. Mbar:  0.005959. Ebar:    0.000000. U: 0.64827.
  MP MC  25% done. Mbar:  0.002627. Ebar:    0.000000. U: 0.48502.
  MP MC  30% done. Mbar:  0.004184. Ebar:    0.000000. U: 0.56640.
  MP MC  35% done. Mbar:  0.002139. Ebar:    0.000000. U: 0.56640.
  MP MC  40% done. Mbar:  0.010061. Ebar:    0.000000. U: 0.53165.
  MP MC  45% done. Mbar:  0.002793. Ebar:    0.000000. U: 0.50601.
  MP MC  50% done. Mbar:  0.011094. Ebar:    0.000000. U: 0.38431.
  MP MC  55% done. Mbar:  0.004709. Ebar:    0.000000. U: 0.38431.
  MP MC  60% done. Mbar:  0.002217. Ebar:    0.000000. U: 0.40403.
  MP MC  65% done. Mbar:  0.006269. Ebar:    0.000000. U: 0.38473.
  MP MC  70% done. Mbar:  0.008258. Ebar:    0.000000. U: 0.38473.
  MP MC  75% done. Mbar:  0.008251. Ebar:    0.000000. U: 0.46254.
  MP MC  80% done. Mbar:  0.004832. Ebar:    0.000000. U: 0.50970.
  MP MC  85% done. Mbar:  0.004251. Ebar:    0.000000. U: 0.50970.
  MP MC  90% done. Mbar:  0.006849. Ebar:    0.000000. U: 0.44416.
  MP MC  95% done. Mbar:  0.007039. Ebar:    0.000000. U: 0.36549.
  MP MC 100% done. Mbar:  0.003013. Ebar:    0.000000. U: 0.27551.
  Correlation lengths:      0.00000     13.70602       108.50
 Simulation finished
 ----------------TIME CONSUMPTION REPORT----------------------
 CATEGORY                 TIME(sec)           PERCENT
  Startup                  8.98E-02               0.1
  Initial                  8.15E+00              12.4
  Measurement              7.36E-02               0.1
  MonteCarlo               4.64E+00               7.1
  Energy                   6.45E-02               0.1
  PrintRestart             4.05E-02               0.1
  SpinCorr                 5.26E+01              80.0
 -------------------------------------------------------------
 Total wall time           6.58E+01      Sampled percent  99.8
 --------------MAIN PROGRAM PHASES TIME REPORT----------------
 CATEGORY                   EXECUTION TIME    TOTAL CPU TIME
  Time for initialization :           0.89              1.63
  Time for initial phase  :           9.59            130.83
  Time for meas. phase    :          60.65            919.81
  Time for cleanup        :           0.00              0.03
 -------------------------------------------------------------
  Time total              :          71.13           1052.30
  Time for one meas. iter :          60.65            919.81
 -------------------MEMORY CONSUMPTION REPORT-----------------------
 130 allocations and 125 deallocations, remaining memory(B):504
 Memory occupation peak: 201460 kB
 For the array: "D_matrix" in routine "ferro_stiffness"
 -----------------END MEMORY CONSUMPTION REPORT---------------------

## Read result collection

We use the `ResultCollection` class to find all simulations run in a given output directory.

In [7]:
res = uppasd.ResultCollection("out")
res

,id,runner,temperature,time_start,time_end,mammos_spindynamics_version
0,run_0,run,10,2025-11-04T13:37:13+01:00,2025-11-04T13:38:23+01:00,0.2.3
1,run_1,run,2,2025-11-04T13:38:23+01:00,2025-11-04T13:39:33+01:00,0.2.3
2,run_2,run,5,2025-11-04T13:39:33+01:00,2025-11-04T13:40:43+01:00,0.2.3
3,run_temparray_0,run_temparray,"[2, 5]",2025-11-04T13:40:43+01:00,2025-11-04T13:43:05+01:00,0.2.3

## Extract and analyze single result

In [8]:
r0 = res[0]
r0

We can extract different values from a `Result` object.

In [9]:
dir(r0)

['T',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'data',
 'inpsd',
 'jfile',
 'last_cumulant',
 'momfile',
 'n_magnetic_atoms',
 'posfile',
 'run_dir',
 'volume']

In [10]:
r0.data

#Iter         1.100000e+01
<M>           8.498713e-03
<M^2>         8.567843e-05
<M^4>         1.074088e-08
U_{Binder}    5.122744e-01
\chi          8.534220e-02
C_v(tot)      0.000000e+00
<E>           0.000000e+00
<E_{exc}>     0.000000e+00
<E_{lsf}>     0.000000e+00
Name: 1, dtype: float64

## Extract and analyze `temparray` Result

In [11]:
r3 = res[3]
r3

We also have a number of attributes and methods.

In [12]:
dir(r3)

['T_array',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'dataframe',
 'n_magnetic_atoms',
 'run_dir',
 'save_output',
 'sub_runs',
 'volume']

We can use the `dataframe` property to collect all information from the sub-runs.

In [13]:
r3.dataframe

,T,iter,<M>[μB],<M^2>,<M^4>,U_{Binder},\chi,C_v(tot),<E>,<E_{exc}>,<E_{lsf}>,C_v[K_B]
0,2.0,11.0,0.008433,0.000085,1.065167e-08,0.506823,0.435522,0.0,0.0,0.0,0.0,0.0
1,5.0,11.0,0.008469,0.000085,1.070570e-08,0.509697,0.172481,0.0,0.0,0.0,0.0,0.0

Individual sub-runs are stored in the `sub_runs` attribute.

In [14]:
r3.sub_runs

[<mammos_spindynamics.uppasd.Result at 0x7f2fade29950>,
 <mammos_spindynamics.uppasd.Result at 0x7f2f62581050>]

We can extract the output of a `temparray` as a `M(T)` file or a `output.csv`.

In [15]:
r3.save_output()

In [16]:
with open("out/run_temparray_0/M(T)") as file:
    print(file.read())

T[K] iter    <M>[μB]          <M^2>           <M^4>         U_{Binder}         \chi          C_v(tot)          <E>          <E_{exc}>       <E_{lsf}>        C_v[K_B]
0002 0011  8.43332510E-03  8.48490195E-05  1.06516665E-08  5.06823187E-01  4.35522062E-01  0.00000000E+00  0.00000000E+00  0.00000000E+00  0.00000000E+00  0.00000000E+00
0005 0011  8.46882366E-03  8.53128869E-05  1.07057000E-08  5.09697013E-01  1.72481279E-01  0.00000000E+00  0.00000000E+00  0.00000000E+00  0.00000000E+00  0.00000000E+00

In [17]:
with open("out/run_temparray_0/output.csv") as file:
    print(file.read())

#mammos csv v2
#----------------------------------------
# Magnetization and heat capacity from UppASD
#----------------------------------------
#ThermodynamicTemperature,SpontaneousMagnetization,,IsochoricHeatCapacity
#https://w3id.org/emmo#EMMO_affe07e4_e9bc_4852_86c6_69e26182a17f,https://w3id.org/emmo/domain/magnetic_material#EMMO_032731f8-874d-5efb-9c9d-6dafaa17ef25,,https://w3id.org/emmo#EMMO_8fc576e1_3984_402b_a548_be921b4e1bf4
#K,A / m,,J / K
T,Ms,U_binder,Cv
2.0,6781.890220846211,0.506823187,0.0
5.0,6810.437363765927,0.509697013,0.0